# -*- coding: utf-8 -*-
"""Gut3_image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PpJoEmQk7_oKnJuLDLwsxrMJyJuo-Shf
"""

!pip install openai python-dotenv

from google.colab import files

uploaded = files.upload()

import os
from dotenv import load_dotenv

load_dotenv()
os.environ["OPENAI_API_KEY"] = ""

os.getenv('OPENAI_API_KEY')

import openai

openai.api_key = ""

import openai
import base64

# Set your API key explicitly
openai.api_key = "your_openai_api_key_here"  # Replace with your actual API key

# Function to encode the image
def encode_image(image_path):
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')

# Path to your uploaded image
image_path = list(uploaded.keys())[0]
base64_image = encode_image(image_path)

# Make API call
response = openai.ChatCompletion.create(
    model="gpt-4o",
    messages=[
        {
            "role": "user",
            "content": [
                {"type": "text", "text": "Analyze this image and provide a detailed description of its contents, highlighting any significant details."},
                {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"}}
            ],
        }
    ],
    max_tokens=500
)

# Display result
analysis = response.choices[0].message.content
print(analysis)

!pip install pyTelegramBotAPI --quiet

!pip install openai==0.28

import openai
import telebot
import os
import base64

# Set your API key directly
  # Replace with your actual key

TelegramBOT_TOKEN = ''
openai.api_key = ""
# Function to encode your uploaded image
def encode_image(image_path):
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')

# Get uploaded image
image_path = list(uploaded.keys())[0]
base64_image = encode_image(image_path)

# Define your SCFA analysis prompt
prompt = f"""
Analyze SCFA levels from microbiome data:
Acetic Acid mean: ['Acetic_acid'].mean()
Propanoic Acid mean: ['Propanoic_acid'].mean()
Butanoic Acid mean: ['Butanoic_acid'].mean()

Using NIH and dietary research:
- Recommend dietary changes to optimize SCFA production.
- Include fiber-rich food examples.
- Suggest foods to avoid if dysbiosis is suspected (low SCFA).
"""
prompt1 = f"""
Patient treated briefly with Ivermectin. Minor microbiota shifts predicted by PICRUSt2; increased SCFA production expected, yet transient bacterial cell death observed in proximal colon.

Concerns:
- Potential immune dysregulation or autoimmune trigger.
- Aim: Preserve microbial diversity, SCFA production, immune regulation.

Suggest dietary adjustments clearly:
- Foods to include specifically for promoting SCFA production and preventing autoimmune risks.
- Foods to strictly avoid to prevent dysbiosis or immune dysregulation.

Explain each recommendation using first principles microbiome science.
"""
prompt2 = f"""
Patient microbiome analysis:
- Low Butyrate levels detected.
- Recent use of ivermectin indicating transient microbial shifts.
- Risk for dysbiosis-induced autoimmunity (e.g., MS).

Based on nutrient dataset (fibrous foods: vegetables, whole grains, nuts; protein sources: fish, legumes; avoid high-calorie fatty foods such as pudding, fatty meats):

Provide explicit dietary recommendations:
1. Foods to emphasize (fiber-rich, SCFA-enhancing).
2. Foods to strictly limit (high-calorie, sugary, processed).
3. Balance protein intake carefully to maintain microbiome health.

Explain recommendations based on gut microbiota principles and SCFA production.
"""
prompt3 = f"""
Visualize the distribution of various nutrients across food categories using an interactive dashboard:
- Data Source: A nutrient dataset aggregated by 'Category', where each nutrient value (Calories, Fat, Protein, Fiber, Sat.Fat, Carbs) is summed per category.
- Metrics to Display:
  • CALORIES: Sum of calories per category.
  • FAT: Sum of fat per category.
  • PROTEIN: Sum of protein per category.
  • FIBER: Sum of fiber per category.
  • SAT.FAT: Sum of saturated fat per category.
  • CARBS: Sum of carbohydrates per category.
- Visualization Layout:
  • Arrange the dashboard in a grid of 2 rows and 3 columns.
  • Each cell in the grid contains a pie chart for one nutrient metric.
  • Use the category names as labels for the pie chart segments.
- Styling Details:
  • Each pie chart should have a title matching its nutrient metric.
  • Apply custom marker colors (e.g., hex codes '#100b' and '#f00560') and outline each slice with a white border (2.5 pixels wide).
- Overall Dashboard:
  • Title: "Category wise distribution of all metrics".
  • Dimensions: 1000 pixels wide and 700 pixels tall.

Based on the above specifications, generate an interactive visual dashboard that displays the nutrient distribution by category.
"""



# Call GPT-4o Multimodal
response = openai.ChatCompletion.create(
    model="gpt-4o",
    messages=[
        {
            "role": "user",
            "content": [
                {"type": "text", "text": "Provide a detailed analysis of this image."},
                 {"type": "text", "text": prompt},
                {"type": "text", "text": prompt1},
                {"type": "text", "text": prompt2},
                 {"type": "text", "text": prompt3},
                {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"}}
            ]
        }
    ],
    max_tokens=500
)

# Print GPT-4o's response
print(response.choices[0].message.content)

!pip install python-dotenv

os.getenv('OPENAI_API_KEY')

from rdkit import DataStructs
from rdkit import Chem
from rdkit.Chem import AllChem

fiber_smiles = 'C(C1C(C(C(O1)O)O)O)O'  # Example: Glucose unit in fiber
fiber_mol = Chem.MolFromSmiles(fiber_smiles)
fiber_fp = AllChem.GetMorganFingerprint(fiber_mol, 2)

scfa_fp = AllChem.GetMorganFingerprint(scfa_mols['Butanoic_acid'], 2)
similarity = DataStructs.TanimotoSimilarity(fiber_fp, scfa_fp)

print(f'Structural similarity (fiber-SCFA): {similarity:.2f}')

import os
import base64
import telebot
import openai
from google.colab import userdata

# Set your API keys
TelegramBOT_TOKEN = userdata.get('TELEGRAM_BOT_TOKEN')
openai.api_key = userdata.get('OPENAI_API_KEY')


bot = telebot.TeleBot(TelegramBOT_TOKEN)

# Function to encode uploaded image
def encode_image(image_path):
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')

# Function to handle image uploads
@bot.message_handler(content_types=['photo'])
def handle_photo(message):
    try:
        # Download the image from Telegram server
        file_info = bot.get_file(message.photo[-1].file_id)
        downloaded_file = bot.download_file(file_info.file_path)

        # Save the file locally
        image_path = 'uploaded_image.jpg'
        with open(image_path, 'wb') as new_file:
            new_file.write(downloaded_file)

        # Encode the image to base64
        base64_image = encode_image(image_path)

        # Define the prompt for analysis
        prompt = f"""
        Analyze SCFA levels from microbiome data:
        Acetic Acid mean: ['Acetic_acid'].mean()
        Propanoic Acid mean: ['Propanoic_acid'].mean()
        Butanoic Acid mean: ['Butanoic_acid'].mean()

        Using NIH and dietary research:
        - Recommend dietary changes to optimize SCFA production.
        - Include fiber-rich food examples.
        - Suggest foods to avoid if dysbiosis is suspected (low SCFA).
        """

        # Call GPT-4o Multimodal API
        response = openai.ChatCompletion.create(
            model="gpt-4o",
            messages=[
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": "Provide a detailed analysis of this image."},
                        {"type": "text", "text": prompt},
                      {
                            "type": "image_url",
                            "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"}
                        }
                    ]
                }
            ],
            max_tokens=500
        )

        # Respond to the Telegram user with the analysis
        bot.reply_to(message, response.choices[0].message.content)
    except Exception as e:
        print(f"An error occurred: {e}")
        bot.reply_to(message, "Sorry, I couldn't process the image or the request.")

# Command to start bot and send a welcome message
@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
    bot.reply_to(message, "Welcome! I can analyze images and provide dietary recommendations based on your microbiome data.")

# Start polling
bot.polling()







####origin source code###

import os
import base64
import telebot
import openai
from google.colab import userdata

# Set your API keys
TelegramBOT_TOKEN = userdata.get('TELEGRAM_BOT_TOKEN')
openai.api_key = userdata.get('OPENAI_API_KEY')


bot = telebot.TeleBot(TelegramBOT_TOKEN)

# Function to encode uploaded image
def encode_image(image_path):
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')

# Function to handle image uploads
@bot.message_handler(content_types=['photo'])
def handle_photo(message):
    try:
        # Download the image from Telegram server
        file_info = bot.get_file(message.photo[-1].file_id)
        downloaded_file = bot.download_file(file_info.file_path)

        # Save the file locally
        image_path = 'uploaded_image.jpg'
        with open(image_path, 'wb') as new_file:
            new_file.write(downloaded_file)

        # Encode the image to base64
        base64_image = encode_image(image_path)

        # Define the prompt for analysis
        prompt = f"""
        Analyze SCFA levels from microbiome data:
        Acetic Acid mean: ['Acetic_acid'].mean()
        Propanoic Acid mean: ['Propanoic_acid'].mean()
        Butanoic Acid mean: ['Butanoic_acid'].mean()

        Using NIH and dietary research:
        - Recommend dietary changes to optimize SCFA production.
        - Include fiber-rich food examples.
        - Suggest foods to avoid if dysbiosis is suspected (low SCFA).
        """

        # Call GPT-4o Multimodal API
        response = openai.ChatCompletion.create(
            model="gpt-4o",
            messages=[
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": "Provide a detailed analysis of this image."},
                        {"type": "text", "text": prompt},
                      {
                            "type": "image_url",
                            "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"}
                        }
                    ]
                }
            ],
            max_tokens=500
        )

        # Respond to the Telegram user with the analysis
        bot.reply_to(message, response.choices[0].message.content)
    except Exception as e:
        print(f"An error occurred: {e}")
        bot.reply_to(message, "Sorry, I couldn't process the image or the request.")

# Command to start bot and send a welcome message
@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
    bot.reply_to(message, "Welcome! I can analyze images and provide dietary recommendations based on your microbiome data.")

# Start polling
bot.polling()

# Define your SCFA analysis prompt
prompt = f"""
Analyze SCFA levels from microbiome data:
Acetic Acid mean: ['Acetic_acid'].mean()
Propanoic Acid mean: ['Propanoic_acid'].mean()
Butanoic Acid mean: ['Butanoic_acid'].mean()

Using NIH and dietary research:
- Recommend dietary changes to optimize SCFA production.
- Include fiber-rich food examples.
- Suggest foods to avoid if dysbiosis is suspected (low SCFA).
"""
prompt1 = f"""
Patient treated briefly with Ivermectin. Minor microbiota shifts predicted by PICRUSt2; increased SCFA production expected, yet transient bacterial cell death observed in proximal colon.

Concerns:
- Potential immune dysregulation or autoimmune trigger.
- Aim: Preserve microbial diversity, SCFA production, immune regulation.

Suggest dietary adjustments clearly:
- Foods to include specifically for promoting SCFA production and preventing autoimmune risks.
- Foods to strictly avoid to prevent dysbiosis or immune dysregulation.

Explain each recommendation using first principles microbiome science.
"""
prompt2 = f"""
Patient microbiome analysis:
- Low Butyrate levels detected.
- Recent use of ivermectin indicating transient microbial shifts.
- Risk for dysbiosis-induced autoimmunity (e.g., MS).

Based on nutrient dataset (fibrous foods: vegetables, whole grains, nuts; protein sources: fish, legumes; avoid high-calorie fatty foods such as pudding, fatty meats):

Provide explicit dietary recommendations:
1. Foods to emphasize (fiber-rich, SCFA-enhancing).
2. Foods to strictly limit (high-calorie, sugary, processed).
3. Balance protein intake carefully to maintain microbiome health.

Explain recommendations based on gut microbiota principles and SCFA production.
"""
prompt3 = f"""
Visualize the distribution of various nutrients across food categories using an interactive dashboard:
- Data Source: A nutrient dataset aggregated by 'Category', where each nutrient value (Calories, Fat, Protein, Fiber, Sat.Fat, Carbs) is summed per category.
- Metrics to Display:
  • CALORIES: Sum of calories per category.
  • FAT: Sum of fat per category.
  • PROTEIN: Sum of protein per category.
  • FIBER: Sum of fiber per category.
  • SAT.FAT: Sum of saturated fat per category.
  • CARBS: Sum of carbohydrates per category.
- Visualization Layout:
  • Arrange the dashboard in a grid of 2 rows and 3 columns.
  • Each cell in the grid contains a pie chart for one nutrient metric.
  • Use the category names as labels for the pie chart segments.
- Styling Details:
  • Each pie chart should have a title matching its nutrient metric.
  • Apply custom marker colors (e.g., hex codes '#100b' and '#f00560') and outline each slice with a white border (2.5 pixels wide).
- Overall Dashboard:
  • Title: "Category wise distribution of all metrics".
  • Dimensions: 1000 pixels wide and 700 pixels tall.

Based on the above specifications, generate an interactive visual dashboard that displays the nutrient distribution by category.
"""

!pip install openai python-dotenv
!pip install pyTelegramBotAPI --quiet
!pip install python-dotenv
!pip install openai==0.28

#####testing code integration#########
import os
import base64
import telebot
import openai
import requests
from google.colab import userdata
import chromadb
chroma_ns = chromadb.Client()


# Set your API keys
TelegramBOT_TOKEN = userdata.get('TELEGRAM_BOT_TOKEN')
openai.api_key = userdata.get('OPENAI_API_KEY')


bot = telebot.TeleBot(TelegramBOT_TOKEN)

# Function to encode uploaded image
def encode_image(image_path):
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')

def get_nih_data(query):
    url = f"https://api.ncbi.nlm.nih.gov/lit/ctxp/v1/pubmed/?format=citation&term={query}"
    response = requests.get(url)
    if response.status_code == 200:
        return response.text
    return "No NIH data found."

# Function to handle image uploads
@bot.message_handler(content_types=['photo'])
def handle_photo(message):
    try:
        # Download the image from Telegram server
        file_info = bot.get_file(message.photo[-1].file_id)
        downloaded_file = bot.download_file(file_info.file_path)

        # Save the file locally
        image_path = 'uploaded_image.jpg'
        with open(image_path, 'wb') as new_file:
            new_file.write(downloaded_file)

        # Encode the image to base64
        base64_image = encode_image(image_path)
        # Retrieve NIH research data
        nih_data = get_nih_data("gut microbiome longevity Akkermansia muciniphila probiotics prebiotics fasting")

        print(nih_data)
        # Optionally, you can save this NIH data to a vector DB
        #chroma_ns.add_to_db(
            #id=str(datetime.datetime.now().timestamp()),
             #content=nih_data,
             #metadata={"source": "NIH PubMed", "timestamp": datetime.datetime.now().isoformat()}
         #)
        prompt0 = f"""
Analyze the provided microbiome test image and related NIH research:
NIH Data: {nih_data}

Provide detailed dietary recommendations, nutrient intake advice, fasting guidance, and foods to avoid for optimal gut microbiome health.
"""

        # Define the prompt for analysis
        prompt1 = f"""
        Analyze SCFA levels from microbiome data:
        Acetic Acid mean: ['Acetic_acid'].mean()
        Propanoic Acid mean: ['Propanoic_acid'].mean()
        Butanoic Acid mean: ['Butanoic_acid'].mean()

        Using NIH and dietary research:
        - Recommend dietary changes to optimize SCFA production.
        - Include fiber-rich food examples.
        - Suggest foods to avoid if dysbiosis is suspected (low SCFA).
        """

        # Call GPT-4o Multimodal API
        response = openai.ChatCompletion.create(
            model="gpt-4o",
            messages=[
                {
                "type": "text",
                "text": """Given an image of an item of Food, analyze the item and generate a JSON output with the following fields: "items", "category", and "nutrients","bacteria","microbiome".
                           Use your understanding of Health trends, styles, and gender preferences to provide accurate and relevant suggestions for how to complete the Good Gut health.
                           The items field should be a list of items that would go well with the item in the picture. Each item should represent a title of an item of food that contains the , color, and gender of the item.
                           The category needs to be chosen between the types in this list: {subcategories}.
                           You have to choose between the genders in this list: [Men, Women, Boys, Girls, Unisex]
                           Do not include the description of the item in the picture. Do not include the ```json ``` tag in the output.

                           Example Input: An image representing a black leather jacket.

                           Example Output: {"items": ["Fitted White Women's T-shirt", "White Canvas Sneakers", "Women's Black Skinny Jeans"], "category": "Jackets", "gender": "Women"}
                           """,
                },
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": "Provide a detailed analysis of this image."},
                        {"type": "text", "text": prompt0},
                        {"type": "text", "text": prompt1},
                      {
                            "type": "image_url",
                            "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"}
                        }
                    ]
                }
            ],
            max_tokens=500
        )

        # Respond to the Telegram user with the analysis
        bot.reply_to(message, response.choices[0].message.content)
    except Exception as e:
        print(f"An error occurred: {e}")
        bot.reply_to(message, "Sorry, I couldn't process the image or the request.")

# Command to start bot and send a welcome message
@bot.message_handler(commands=['start', 'help'])
def send_welcome(message):
    bot.reply_to(message, "Welcome! I can analyze images and provide dietary recommendations based on your microbiome data.")

# Start polling
bot.polling()

import chromadb
import openai
from chromadb.utils.embedding_functions import OpenAIEmbeddingFunction

openai_api_key = ""
embedding_fn = OpenAIEmbeddingFunction(api_key=openai_api_key, model_name="text-embedding-3-small")

client = chromadb.PersistentClient(path="chroma_db")
collection = client.get_or_create_collection(name="nih_gut_health", embedding_function=embedding_fn)

def add_to_db(id, content, metadata):
    collection.add(
        documents=[content],
        metadatas=[metadata],
        ids=[id]
    )

def query_db(query_text, n_results=3):
    results = collection.query(
        query_texts=[query_text],
        n_results=n_results
    )
    return results

